### ISSUE TITLE
Develop facebook connection to be related with our Ex_User model

### ISSUE THREAD

**Issue by jyeoniii** [swsnu/swpp17-team9#25]
The current implementation of Facebook connection only supports logging in, and saving the basic user information to our database.
When a user signs up (with successful mySNU authentication), they should be able to connect their Facebook account to this service by logging in to Facebook.

### TODO
- [x] Add fields for Facebook to our Ex_User model.
- [x] Change social auth pipeline to build a relation between Ex_User and the social auth user model.
- [x] Add extra information 'friends' to 'SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS' to retrieve more information from facebook connection.
- [x] With the information above, Add many-to-many relationship for user friends.
- [ ] Update friends status whenever a user signs in.
