### ISSUE TITLE
Implement Message Components

### ISSUE THREAD

**Issue by matues00** [swsnu/swpp17-team9#40]
Message service is important with people who wants to participate in some mo-ims.
This issue will take care of the message services.

## TODO
- [x] The logined user can be able to reach message page when he/she wants.
- [x] The logined user can send messages to other users.
- [ ] The logined user can be able to notice when the new message has been received
